#+title: Вырезаем функции из объектного файла

=funcut0= — это маленькая программа-эксперимент, которая предназначена для вырезания функций из объектных файлов и их запуска. Программа работает только с функциями типа uint → uint → uint (где uint — unsigned int). Ясно, что можно приспособить её для других задач, главным здесь был /принцип/.

* Принцип работы
Принцип работы в целом весьма прост. Функция, как и всё в машинном коде — это набор байт. Только в отличие от строки или числа, функция содержит набор байт, кодирующих инструкции (опкоды). Всё, что нам необходимо — считать этот набор байт, а затем выполнить его, как обычный код.

Сложности реализации этой идеи кроются в деталях. Нашу функцию нельзя считывать куда угодно. Считай её в переменную — и программа завершится из-за ошибки сегментации. Так получится потому, что области памяти, в которых находятся переменные, обычно защищены от исполнения. Если переменная глобальная, то она хранится в секции =.data= (или =.bss=). Локальные переменные хранятся в стеке. Содержимое секции =.data= и стека по умолчанию выполнять нельзя. (Но в целом стек сделать исполняемым весьма просто: для этого нужно передать флаг =-zexecstack= или воспользоваться утилитой =execstack=, однако в данной задаче это не требуется.)

Выделение памяти через аллокаторы общего назначения (например, =malloc= или =jemalloc=) тоже не сработает: эта память будет выделяться для чтения и записи, но не выполнения.

Поэтому выделять память нужно при помощи системных вызовов, я использовал =mmap=. Вообще-то, =mmap= используется для отображения файлов в память, но использование флага =MAP_ANON= позволяет выделить память без привязки к файлам. Вызов =mmap= для выделения памяти примет вид:
#+begin_src c
  void *result = mmap(NULL, size,
                      PROT_READ | PROT_WRITE | PROT_EXEC,
                      MAP_PRIVATE | MAP_ANON,
                      -1, 0);
#+end_src

В строке 1 устанавливаются параметры =addr= и =size=. Передача =NULL= в качестве адреса сообщает ядру, что расположение выделяемой памяти должно быть выбрано автоматически.

В строке 2 устанавливаются разрешённые операции над памятью. В нашем случае это полный набор — чтение, запись, выполнение.

В строке 3 устанавливаются два флага. Первый сообщает, что память будет частной, а второй — что она выделяется без привязки к файлу. Поэтому параметры в строке 4, оба связанные с файлом, установлены в специальные значения.

После того, как память выделена, остаётся только записать в неё данные и отправить на исполнение, что не составляет труда.

* Использование
Рядом с =funcut= лежит подопытная программа — =subject0=. Она содержит определение двух функций: сложения и умножения. Если скомпилировать цель =sbj= (=make sbj=), то появится объектный файл =sbj.o=.

Чтобы теперь вырезать из него функцию, необходимо знать три параметра: позицию начала, позицию конца и смещение (оно не обязательно, но добавляет удобства). Узнать эти параметры можно с помощью утилиты =readelf=. Сначала запустим её с флагом =-s=, чтобы посмотреть таблицу символов:
#+begin_example
  $ readelf -s sbj.o
  Таблица символов «.symtab» содержит 15 элементов:
     Чис:    Знач           Разм Тип     Связ   Vis      Индекс имени
       0: 0000000000000000     0 NOTYPE  LOCAL  DEFAULT  UND 
       1: 0000000000000000     0 FILE    LOCAL  DEFAULT  ABS subject0.c
       2: 0000000000000000     0 SECTION LOCAL  DEFAULT    1 
  […]
      12: 0000000000000000     0 SECTION LOCAL  DEFAULT   12 
      13: 0000000000000000    20 FUNC    GLOBAL DEFAULT    1 add
      14: 0000000000000014    19 FUNC    GLOBAL DEFAULT    1 mult
#+end_example

Здесь важны два столбца: «Знач» и «Разм». «Знач», что бы ни говорило его название, содержит адрес символа /в его секции/. «Разм» содержит размер символа в байтах. Важно заметить, что адреса указаны в шестнадцатеричной системе, а размеры — в десятичной. (Зачем так делать — для меня секрет.)

Применяем базовую математику и получаем адреса функций: [0x00, 0x14] и [0x14, 0x27], соответственно.

Но всё ли это? Ещё нет. Нужно обратить внимание, что это /адреса внутри секции/. То есть реальный адрес в файле будет другим: к нашим адресам нужно ещё добавить адрес, с которого начинается секция.

Воспользуемся помощью =readelf= и посмотрим список секций:
#+begin_example
  Имеется 19 заголовков раздела, начиная со смещения 0x6d0:

  Заголовки разделов:
    [Нм] Имя               Тип              Адрес             Смещение
         Размер            Разм.Ent         Флаги  Ссылк Инфо  Выравн
    [ 0]                   NULL             0000000000000000  00000000
         0000000000000000  0000000000000000           0     0     0
    [ 1] .text             PROGBITS         0000000000000000  00000040
         0000000000000027  0000000000000000  AX       0     0     1
    [ 2] .data             PROGBITS         0000000000000000  00000067
         0000000000000000  0000000000000000  WA       0     0     1
    [ 3] .bss              NOBITS           0000000000000000  00000067
         0000000000000000  0000000000000000  WA       0     0     1
#+end_example

Смотрим в столбец «Выравн» и видим, что секция с кодом — =.text= начинается на 0x40.

Для работы =funcut= этого достаточно. Проверим работу первой функции (сложение):
#+begin_example
  $ ./fc0 sbj.o 0 14 40
  Read 14 bytes from 40 to 54
  Ok

  55 48 89 e5 89 7d fc 89 
  75 f8 8b 55 fc 8b 45 f8 
  1 d0 5d c3 

  > 7
#+end_example

А затем помучаем вторую функцию (умножение):
#+begin_example
  $ ./fc0 sbj.o 14 27 40
  Read 13 bytes from 54 to 67
  Ok

  55 48 89 e5 89 7d fc 89 
  75 f8 8b 45 fc f af 45 
  f8 5d c3 

  > a
#+end_example

Сначала вывод может показаться странным, но всё правильно: программа принимает все числа в шестнадцатеричном формате и выводит их также. Префикс =0x= она не использует, он был бы излишним.

Результаты работы функций верны, ведь действительно: 0d2 + 0d5 = 0x7, 0d2 × 0d5 = 0xa.
